PATCH http://localhost:5004/api/studies/hello/habits/4304305e-a782-4601-b0bb-f26ad2bcabc4/
Content-Type: application/json

{
    "deletedAt": "2025-02-03T06:41:26.111Z"
}

###
POST http://localhost:5004/api/studies/hello/habits/test3/check/today
Content-Type: application/json

{
    "status":true,
    "habitName":"잠자기"
}

###

GET http://localhost:5004/api/studies/hello/habits/test/check?start=2025-02-04T00:00:00.000Z&end=2025-02-07T00:00:00.000Z

