GET https://five-forest-team1.onrender.com/api/studies?page=2
###
POST http://localhost:5004/api/studies/6a6046af-f969-48a2-9c29-317049140ecf/habits
Content-Type: application/json

{
  "studyId": "11267ffc-5899-4e8b-8117-7620ae5e9c27", 
  "name": "파이썬 강의 듣기"
}
